export const UPDATE_CART_DETAIL = "UPDATE_CART_DETAIL"
export const REMOVE_CART_DETAIL = "REMOVE_CART_DETAIL"
export const INCREASE_CART_DETAIL = "INCREASE_CART_DETAIL"
export const DECREASE_CART_DETAIL = "DECREASE_CART_DETAIL"
export const EMPTY_CART = "EMPTY_CART"

